baseURL = "https://zhuoyw.github.io/blog/"
#baseURL = "https://blog.youwei.xyz/"
canonifyURLs = true
languageCode = "zh-cn"
title = "用之则行 舍之则藏"
theme = "hyde"
copyright = "Youwei Zhuo"

[Author]
	name = "Youwei Zhuo"

[Menus]
	main = [
		{ Name = "Posts", URL = "/posts"},
		{ Name = "Tags", URL = "/tags"}
	]

[Permalinks]
	posts = "/posts/:year/:month/:day/:filename/"

[taxonomies]
	tag = "tags"

[params]
	description = "Blog de Youwei Zhuo"
	layoutReverse = true
	themeColor = "theme-base-08"
	github = "https://github.com/zhuoyw"
	image = "/cat.gif"
	
	
